run_mode: "inf"
num_epochs: 0
offline_log: False
mode: autoencodergen
load_dir: "/workspace/GOFA/saved_exp/2024-09-26_00:13:58.388633_395/best_ckpt.pth"
base_llm: "mistral7b"
load_model: True
last_save: False
batch_size: 1

sample_size_per_task: 100
llm_max_length: 1024
train_data_multiples: 1.0
train_task_names:
  - cora_node
hops: 3
train_max_nodes_per_hops: 5
ways: -1
instructs: True
selections: True

eval_task_names:
  - ml1m

inf_sample_size_per_task:
  - 15000

inf_hops:
  - 1

inf_max_nodes_per_hops:
  - 15


inf_ways:
  - -1

inf_instructs:
  - False


inf_selections:
  - False
