run_mode: "ft"
load_model: True
load_dir: "yourpretrained_model_path"
last_epochs: 0
num_epochs: 1
mode: "autoencoder"
batch_size: 1
lr: 0.0001
l2: 0.1
train_data_multiples: 1.0
train_task_names:
  - arxiv
  - cora_node
  - cora_link
  - pubmed_node
  - pubmed_link
  - wikics
  - wn18rr
  - fb15k237
  - ml1m
  - products
sample_size_per_task:
  - 16000
  - 1200
  - 15000
  - 1300
  - 20000
  - 8000
  - 20000
  - 20000
  - 15000
  - 10000
hops:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 1
  - 3

train_max_nodes_per_hops:
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 15
  - 5


ways: -1
selections: False
instructs: False

eval_task_names:
  - arxiv
  - cora_node
  - cora_link
  - pubmed_node
  - pubmed_link
  - wikics
  - wn18rr
  - fb15k237
  - ml1m
  - products
inf_sample_size_per_task: 20
inf_hops:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 1
  - 3

inf_max_nodes_per_hops:
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 15
  - 5

inf_ways:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1

inf_instructs:
  - False
  - False
  - False
  - False
  - False
  - False
  - False
  - False
  - False
  - False

inf_selections:
  - False
  - False
  - False
  - False
  - False
  - False
  - False
  - False
  - False
  - False

dec_lora: True